FROM openresty/openresty:centos
MAINTAINER renyineng 7332039@qq.com
RUN yum install -y bind-utils
RUN mkdir -p /var/log/openresty
# RUN /usr/local/openresty/luajit/bin/luarocks install luarocks
# RUN /usr/local/openresty/luajit/bin/luarocks install penlight
# RUN /usr/local/openresty/luajit/bin/luarocks install luafilesystem